---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: alma9.2
    image: almalinux:9.2-20230512
    # pre_build_image: true
  - name: rocky9.2
    image: rockylinux:9.2.20230513
  - name: rocky8.8
    image: rockylinux:8.8.20230518
  - name: ubuntu2004
    image: ubuntu:20.04
  - name: ubuntu2204
    image: ubuntu:22.04
provisioner:
  name: ansible
verifier:
  name: ansible
